// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABiWBvRnvP9t3LlqC6SUcl-SFOIRUqSDA',
    appId: '1:194618817928:web:b5b0010dffbb16da694e3d',
    messagingSenderId: '194618817928',
    projectId: 'fir-8f625',
    authDomain: 'fir-8f625.firebaseapp.com',
    storageBucket: 'fir-8f625.firebasestorage.app',
    measurementId: 'G-M9W4JES97E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfr2YFfAq8bNR5THBrPPGNOz9SDhtLdH8',
    appId: '1:194618817928:android:a69931d51dfbf482694e3d',
    messagingSenderId: '194618817928',
    projectId: 'fir-8f625',
    storageBucket: 'fir-8f625.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ziDmMNav0UFK9JxOJYGQ4VkJBhuhbYA',
    appId: '1:194618817928:ios:685c62c9032d7ae0694e3d',
    messagingSenderId: '194618817928',
    projectId: 'fir-8f625',
    storageBucket: 'fir-8f625.firebasestorage.app',
    androidClientId: '194618817928-pedsl3erpg1o19pdohjel6oqa8d4elhm.apps.googleusercontent.com',
    iosClientId: '194618817928-49vtt2ft2fg0f4j7jmeojh6hqpf3r5vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
